package youtube

import (
   "fmt"
   "io"
   "testing"
)

const desc = "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
"50 Words For Snow\n\n" +
"℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
"Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
"Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube."

func TestAndroid(t *testing.T) {
   play, err := Android.Player("MeJVWBSsPAY")
   if err != nil {
      t.Fatal(err)
   }
   form := play.StreamingData.AdaptiveFormats[0]
   if err := form.Write(io.Discard); err != nil {
      t.Fatal(err)
   }
}

func TestEmbed(t *testing.T) {
   play, err := Embed.Player("QWlNyzzwgcc")
   if err != nil {
      t.Fatal(err)
   }
   form := play.StreamingData.AdaptiveFormats[0]
   if err := form.Write(io.Discard); err != nil {
      t.Fatal(err)
   }
}

func TestMweb(t *testing.T) {
   play, err := Mweb.Player("XeojXq6ySs4")
   if err != nil {
      t.Fatal(err)
   }
   if play.VideoDetails.ViewCount == 0 {
      t.Fatalf("%+v\n", play)
   }
   if play.VideoDetails.Title != "Snowflake" {
      t.Fatalf("%+v\n", play)
   }
   if play.VideoDetails.ShortDescription != desc {
      t.Fatalf("%+v\n", play)
   }
}

func TestSearch(t *testing.T) {
   s, err := Mweb.Search("oneohtrix point never along")
   if err != nil {
      t.Fatal(err)
   }
   for _, i := range s.Items() {
      fmt.Println(i.CompactVideoRenderer)
   }
}
